'use strict';
const token=location.pathname.split('/').filter(Boolean).at(-1),message=document.querySelector('#message'),pickerArea=document.querySelector('#pickerArea'),fileInput=document.querySelector('#files'),folderInput=document.querySelector('#folder'),sendButton=document.querySelector('#send'),cancelButton=document.querySelector('#cancel'),bar=document.querySelector('#progress'),detail=document.querySelector('#detail');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms)),fmt=n=>n>=1073741824?(n/1073741824).toFixed(2)+' GB':n>=1048576?(n/1048576).toFixed(1)+' MB':n>=1024?(n/1024).toFixed(1)+' KB':n+' B';
let ws,pc,channel,remoteIce,transferWindow,files=[],active=false,ackWaiter,resumeBatch=null,resumeDraft=null,peerGeneration=0,reconnectAttempt=0,reconnectTimer=null,cancelRequested=false,peerRecoveryTimer,peerStableTimer,peerRecoveryAttempts=0;
const nativeReadRequests=new Map();let nativeReadSequence=0,nativeAutoStarted=false,nativeAutoTimer;
function nativeMessage(data){try{window.chrome?.webview?.postMessage(data);}catch{}}
function show(text){message.textContent=text;nativeMessage({type:'status',text});}
function nativeReadFile(fileId,offset,length){if(!Number.isSafeInteger(offset)||!Number.isSafeInteger(length)||offset<0||length<1||length>48*1024)return Promise.reject(Error('読み出し位置が不正です。'));const requestId='r'+(++nativeReadSequence);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{nativeReadRequests.delete(requestId);reject(Error('送信元PCからファイルを読み出せません。'));},30000);nativeReadRequests.set(requestId,{resolve:value=>{clearTimeout(timer);nativeReadRequests.delete(requestId);resolve(value);},reject:error=>{clearTimeout(timer);nativeReadRequests.delete(requestId);reject(error);}});try{window.chrome.webview.postMessage({type:'file-read',requestId,fileId,offset,length});}catch(error){nativeReadRequests.get(requestId)?.reject(error);}});}
window.chrome?.webview?.addEventListener('message',event=>{const data=event.data;if(data?.type!=='file-read-result'||typeof data.requestId!=='string')return;const pending=nativeReadRequests.get(data.requestId);if(!pending)return;if(data.error){pending.reject(Error(String(data.error)));return;}try{const binary=atob(String(data.base64||'')),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);pending.resolve(bytes.buffer);}catch(error){pending.reject(error);}});
window.EZSetNativeFiles=function(items,sender){if(!Array.isArray(items)||items.length<1||items.length>2000)throw Error('送信ファイル一覧が不正です。');window.EZNativeFiles=items.map(item=>({name:item.name,size:item.length,webkitRelativePath:item.relativePath,ezNativeId:item.id,ezNativeSha256:item.sha256,slice(start,end){const offset=Number(start),length=Number(end)-offset;return{arrayBuffer:()=>nativeReadFile(item.id,offset,length)};}}));document.querySelector('#sender').value=String(sender||'EZ Converter').slice(0,64);document.querySelectorAll('#pickerArea label').forEach(label=>label.hidden=true);sendButton.hidden=true;document.querySelector('#selection').textContent=items.length+'件 · '+fmt(items.reduce((sum,item)=>sum+item.length,0))+' · アプリから送信';window.EZNativeAutoSend=true;updateFiles();maybeAutoSend();clearInterval(nativeAutoTimer);nativeAutoTimer=setInterval(()=>{maybeAutoSend();if(nativeAutoStarted)clearInterval(nativeAutoTimer);},250);};
function maybeAutoSend(){if(!window.EZNativeAutoSend||nativeAutoStarted||channel?.readyState!=='open'||!window.EZNativeFiles?.length)return;nativeAutoStarted=true;setTimeout(()=>transfer(),0);}
function sendSignal(data){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data));}
function sendData(data){if(channel?.readyState==='open')channel.send(JSON.stringify(data));}
function waitFor(type,timeout=120000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{if(ackWaiter?.type===type)ackWaiter=null;reject(Error('相手から応答がありません。受信状態を確認してください。'));},timeout);ackWaiter={type,resolve:value=>{clearTimeout(timer);ackWaiter=null;resolve(value);},reject:error=>{clearTimeout(timer);ackWaiter=null;reject(error);}};});}
function updateFiles(){const candidates=window.EZNativeFiles||[...fileInput.files,...folderInput.files],seen=new Set();files=candidates.filter(file=>{const path=file.webkitRelativePath||file.name,key=path.toLocaleLowerCase();if(seen.has(key))return false;seen.add(key);return true;});document.querySelector('#selection').textContent=files.length+'件 · '+fmt(files.reduce((sum,file)=>sum+file.size,0));sendButton.disabled=files.length===0||active;}
fileInput.addEventListener('change',updateFiles);folderInput.addEventListener('change',updateFiles);
function startPeer(){const previousPc=pc,previousFlow=transferWindow;peerGeneration++;previousFlow?.fail(Error('P2P接続を再確立しています。'));try{previousPc?.close();}catch{}channel=null;pc=new RTCPeerConnection({iceServers:window.EZIceServers});remoteIce=window.EZRemoteIceQueue(pc);transferWindow=window.EZTransferWindow();const flow=transferWindow;pc.ondatachannel=event=>{channel=event.channel;channel.binaryType='arraybuffer';channel.onopen=()=>show('P2P直接接続が確立しました。送信するファイルを選択できます。');channel.onclose=()=>{const error=Error('P2P接続が終了しました。');flow.fail(error);ackWaiter?.reject(error);};channel.onmessage=event=>{if(typeof event.data!=='string')return;try{const data=JSON.parse(event.data);if(data.type==='request-files'){pickerArea.hidden=false;show('送信先: '+data.name+' · ファイルを選択してください。');}else if(data.type==='resume-start'){resumeDraft={id:data.id,state:data.state,offsets:{}};}else if(data.type==='resume-offset'){if(!resumeDraft||typeof data.fileId!=='string'||!Number.isSafeInteger(data.offset)||data.offset<0||Object.keys(resumeDraft.offsets).length>=2000)throw Error('再開位置の情報が不正です。');resumeDraft.offsets[data.fileId]=data.offset;}else if(data.type==='resume-end'){const draft=resumeDraft;resumeDraft=null;if(draft)continueResume(draft).catch(error=>{show(error.message);sendData({type:'cancel'});resumeBatch=null;});}else if(data.type==='accepted'&&ackWaiter?.type==='accepted')ackWaiter.resolve(data);else if(data.type==='rejected'){resumeBatch=null;ackWaiter?.reject(Error(data.message||'受信が許可されませんでした。'));show(data.message||'受信が許可されませんでした。');}else if(data.type==='ack')flow.acknowledge(Number(data.offset));else if(data.type==='file-accepted'&&ackWaiter?.type==='file-accepted')ackWaiter.resolve(data);else if(data.type==='done'){if(ackWaiter?.type==='done')ackWaiter.resolve(data);else{resumeBatch=null;bar.value=100;show('受信が完了しました。');}}else if(data.type==='error'){const error=Error(String(data.message||'通信エラー'));ackWaiter?.reject(error);flow.fail(error);show('送信先でエラー: '+error.message);}}catch(error){show(error.message);flow.fail(error);}};};pc.onicecandidate=event=>{if(event.candidate)sendSignal({type:'candidate',candidate:event.candidate.candidate,sdpMid:event.candidate.sdpMid,sdpMLineIndex:event.candidate.sdpMLineIndex});};pc.onconnectionstatechange=()=>{if(pc?.connectionState==='connected')verifyDirect().catch(()=>{});else if(pc?.connectionState==='failed')window.EZReportIceFailure(pc,show);};}
async function verifyDirect(){if(!pc)return;const stats=await pc.getStats();let pair;for(const item of stats.values())if(item.type==='transport'&&item.selectedCandidatePairId)pair=stats.get(item.selectedCandidatePairId);if(!pair)return;const local=stats.get(pair.localCandidateId),remote=stats.get(pair.remoteCandidateId);if(local?.candidateType==='relay'||remote?.candidateType==='relay'){if(!window.EZAllowRelay){pc.close();show('中継候補が選ばれたため接続を終了しました。ファイルは中継しません。');return;}show('P2P接続中（設定したTURNサーバーを経由）');return;}show('P2P直接接続中（'+(local?.candidateType||'peer')+' ↔ '+(remote?.candidateType||'peer')+'）');}
async function acceptOffer(offer){await remoteIce.setRemoteDescription(offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);sendSignal({type:'answer',sdp:answer.sdp});}
function connect(){if(ws&&[WebSocket.CONNECTING,WebSocket.OPEN].includes(ws.readyState))return;const scheme=location.protocol==='https:'?'wss:':'ws:';ws=new WebSocket(scheme+'//'+location.host+'/rtc/'+encodeURIComponent(token)+'?role=guest');ws.onopen=()=>{reconnectAttempt=0;show('送信先PCとの直接接続を待っています...');};ws.onmessage=event=>{try{const data=JSON.parse(event.data);if(data.type==='peer-ready')startPeer();else if(data.type==='peer-left'){peerGeneration++;const error=Error('送信先との接続が切れました。再接続すると続きから再開できます。');transferWindow?.fail(error);ackWaiter?.reject(error);try{pc?.close();}catch{}pc=null;channel=null;remoteIce=null;show(resumeBatch?'接続が切れました。選んだファイルを保持しています。送信元が再接続すると続きから送ります。':'送信先との接続が終了しました。同じURLで再接続できます。');}else if(data.type==='offer'&&pc)acceptOffer(data).catch(error=>show(error.message));else if(data.type==='answer'&&pc)remoteIce.setRemoteDescription(data).catch(error=>show(error.message));else if(data.type==='candidate'&&pc)remoteIce.addCandidate({candidate:data.candidate,sdpMid:data.sdpMid,sdpMLineIndex:data.sdpMLineIndex}).catch(error=>show(error.message));}catch(error){show(error.message);}};ws.onclose=()=>{show('接続が一時的に切れました。選択したファイルは保持し、再接続しています...');if(reconnectTimer)clearTimeout(reconnectTimer);const delay=Math.min(30000,1000*2**Math.min(reconnectAttempt++,5));reconnectTimer=setTimeout(()=>{reconnectTimer=null;connect();},delay);};ws.onerror=()=>show('接続案内へ接続できません。ネットワークを再確認しています...');}
async function hashFiles(){if(window.EZNativeFiles)return window.EZNativeFiles.map(file=>({file,id:Array.from(crypto.getRandomValues(new Uint8Array(16)),value=>value.toString(16).padStart(2,'0')).join(''),relativePath:file.webkitRelativePath||file.name,length:file.size,sha256:file.ezNativeSha256}));const result=[];for(let index=0;index<files.length;index++){const file=files[index],hash=new EZSha256();show('送信前にファイルを確認しています ('+(index+1)+'/'+files.length+'): '+file.name);for(let offset=0;offset<file.size;offset+=1024*1024){hash.update(new Uint8Array(await file.slice(offset,offset+1024*1024).arrayBuffer()));await sleep(0);}const id=Array.from(crypto.getRandomValues(new Uint8Array(16)),value=>value.toString(16).padStart(2,'0')).join('');result.push({file,id,relativePath:file.webkitRelativePath||file.name,length:file.size,sha256:hash.hex()});}return result;}
function captureContext(){return{channel,flow:transferWindow,generation:peerGeneration};}
function assertContext(context){if(!context.channel||channel!==context.channel||context.channel.readyState!=='open'||context.generation!==peerGeneration)throw Error('P2P接続が切れました。再接続すると続きから再開できます。');}
function sendControl(context,message){assertContext(context);context.channel.send(JSON.stringify(message));}
async function sendPreparedBatch(batch,offsets,context){let completed=0;for(const item of batch.prepared){const offsetValue=offsets[item.id]??0;if(!Number.isSafeInteger(offsetValue)||offsetValue<0||offsetValue>item.length)throw Error('受信側から不正な再開位置が返されました。');let offset=offsetValue;context.flow.reset(offset);bar.value=batch.total?100*(completed+offset)/batch.total:100;detail.textContent=fmt(completed+offset)+' / '+fmt(batch.total);while(offset<item.length){const windowEnd=Math.min(item.length,offset+context.flow.windowBytes);while(offset<windowEnd){assertContext(context);const length=Math.min(48*1024,item.length-offset),buffer=await item.file.slice(offset,offset+length).arrayBuffer();assertContext(context);sendControl(context,{type:'chunk',fileId:item.id,offset,length});context.channel.send(buffer);offset+=length;context.flow.markSent(offset);while(context.channel.bufferedAmount>context.flow.windowBytes*2&&context.channel.readyState==='open')await sleep(10);assertContext(context);}await context.flow.waitFor(windowEnd);const received=context.flow.acknowledgedOffset;bar.value=batch.total?100*(completed+received)/batch.total:100;detail.textContent=fmt(completed+received)+' / '+fmt(batch.total);nativeMessage({type:'progress',completed:completed+received,total:batch.total,detail:item.relativePath});show('直接送信中: '+item.relativePath);}sendControl(context,{type:'file-complete',fileId:item.id});await waitFor('file-accepted');if(item.file.ezNativeId)nativeMessage({type:'file-closed',fileId:item.file.ezNativeId});completed+=item.length;}sendControl(context,{type:'complete'});await waitFor('done');bar.value=100;show('送信完了。相手のPCでファイルの整合性を確認して保存しました。');nativeMessage({type:'complete'});}
async function continueResume(draft){const batch=resumeBatch;if(!batch){sendData({type:'resume-unavailable'});show('前回選んだファイルがこのページにありません。再選択して送信してください。');return;}if(draft.state==='completed'){resumeBatch=null;bar.value=100;show('前回の転送はすでに完了しています。');return;}if(draft.state==='rejected'){resumeBatch=null;show('前回の転送は受信側で拒否されました。');return;}if(draft.state!=='pending'&&draft.state!=='accepted'){sendData({type:'resume-unavailable'});return;}for(const id of Object.keys(draft.offsets))if(!batch.prepared.some(item=>item.id===id))throw Error('受信側の再開情報が送信ファイルと一致しません。');if(draft.state==='pending'){show('受信側の許可を待っています。許可後に続きから再開します。');await waitFor('accepted');}while(active)await sleep(20);if(!resumeBatch||resumeBatch!==batch)return;active=true;sendButton.disabled=true;cancelButton.disabled=false;cancelRequested=false;const context=captureContext();try{show('接続を復旧しました。受信位置から再開します...');await sendPreparedBatch(batch,draft.offsets,context);if(resumeBatch===batch)resumeBatch=null;}catch(error){context.flow?.fail(error);const interrupted=resumeBatch===batch&&(context.channel!==channel||context.channel?.readyState!=='open'||context.generation!==peerGeneration);if(!interrupted){if(context.channel?.readyState==='open'&&context.channel===channel)context.channel.send(JSON.stringify({type:'cancel'}));resumeBatch=null;}show(interrupted?'接続が再び切れました。10分以内に再接続すると続きから再開できます。':error.message);}finally{active=false;cancelButton.disabled=true;updateFiles();}}
async function transfer(){if(active||channel?.readyState!=='open')return;active=true;cancelRequested=false;sendButton.disabled=true;cancelButton.disabled=false;bar.value=0;const context=captureContext();let batch=null;try{if(files.length<1||files.length>2000)throw Error('一度に送信できるファイルは2,000件までです。');const prepared=await hashFiles(),total=prepared.reduce((sum,item)=>sum+item.length,0),sender=document.querySelector('#sender').value.trim()||'ブラウザーのゲスト';batch={prepared,total,sender};resumeBatch=batch;assertContext(context);sendControl(context,{type:'offer-start',sender});for(const item of prepared){while(context.channel.bufferedAmount>256*1024&&context.channel.readyState==='open')await sleep(20);sendControl(context,{type:'offer-file',file:{id:item.id,relativePath:item.relativePath,length:item.length,sha256:item.sha256}});}sendControl(context,{type:'offer-end'});show('送信先のPCで受信が許可されるのを待っています...');await waitFor('accepted');await sendPreparedBatch(batch,{},context);if(resumeBatch===batch)resumeBatch=null;}catch(error){context.flow?.fail(error);const interrupted=!cancelRequested&&batch&&resumeBatch===batch&&(context.channel!==channel||context.channel?.readyState!=='open'||context.generation!==peerGeneration);if(!interrupted){if(context.channel?.readyState==='open'&&context.channel===channel)context.channel.send(JSON.stringify({type:'cancel'}));if(batch&&resumeBatch===batch)resumeBatch=null;show(error.message);}else show('接続が切れました。選んだファイルはこのページに保持されています。10分以内に再接続すると続きから送れます。');}finally{active=false;cancelButton.disabled=true;updateFiles();}}
sendButton.addEventListener('click',()=>transfer());cancelButton.addEventListener('click',()=>{cancelRequested=true;resumeBatch=null;const error=Error('送信をキャンセルしました。');sendData({type:'cancel'});ackWaiter?.reject(error);transferWindow?.fail(error);});
const startPeerWithRecovery=startPeer;
startPeer=function(){startPeerWithRecovery();const connection=pc,reportState=connection.onconnectionstatechange;connection.onconnectionstatechange=()=>{if(pc!==connection)return;reportState?.();if(connection.connectionState==='connected'){clearTimeout(peerRecoveryTimer);peerRecoveryTimer=null;clearTimeout(peerStableTimer);peerStableTimer=setTimeout(()=>{if(pc===connection&&connection.connectionState==='connected')peerRecoveryAttempts=0;},30000);}else if(connection.connectionState==='failed'||connection.connectionState==='disconnected'){if(connection.connectionState==='failed')window.EZReportIceFailure(connection,show);if(!peerRecoveryTimer&&peerRecoveryAttempts<2)peerRecoveryTimer=setTimeout(()=>{peerRecoveryTimer=null;if(pc!==connection||!['disconnected','failed'].includes(connection.connectionState))return;peerRecoveryAttempts++;show('P2P接続が中断しました。送信ファイルを保持して再接続しています...');if(ws?.readyState===WebSocket.OPEN)ws.close();},8000);}};};
const connectWithPeerLeftRecovery=connect;
connect=function(){
  connectWithPeerLeftRecovery();
  const socket=ws,receiveMessage=socket.onmessage,closeWhenDone=socket.onclose;
  let queueFull=false;
  socket.onmessage=event=>{
    receiveMessage?.(event);
    try{
      const data=JSON.parse(event.data);
      if(data.type==='queued')show('順番待ちです（受付時点で'+(Number(data.position)||'—')+'番目）。前の受信者の転送が終わると、自動で接続します...');
      else if(data.type==='queue-full'){queueFull=true;show('待機中の受信者が多いため接続できません。しばらくしてから、もう一度このURLを開いてください。');}
      else if(data.type==='peer-left')setTimeout(()=>{if(ws===socket&&socket.readyState===WebSocket.OPEN)socket.close();},0);
    }catch{}
  };
  socket.onclose=event=>{if(queueFull)return;closeWhenDone?.(event);};
};
const transferBeforeNativeBridge=transfer;
transfer=async function(){await transferBeforeNativeBridge();if(!window.EZNativeAutoSend)return;if(message.textContent.startsWith('送信完了'))nativeMessage({type:'complete'});else if(cancelRequested)nativeMessage({type:'cancelled'});else if(!resumeBatch&&!active)nativeMessage({type:'failed',message:message.textContent||'P2P送信に失敗しました。'});};
const continueResumeBeforeNativeBridge=continueResume;
continueResume=async function(draft){await continueResumeBeforeNativeBridge(draft);if(!window.EZNativeAutoSend||resumeBatch||active)return;if(message.textContent.includes('完了'))nativeMessage({type:'complete'});else nativeMessage({type:'failed',message:message.textContent||'P2P再開に失敗しました。'});};
connect();
